Add rails conf 2023 AI talk
arbox/machine-learning-with-ruby pull request #41
Opened 2023-06-09 04:23 UTC by thedayisntgray

I want to contribute to this list and help the maintainers, so:

- [x] I've accepted the terms of the `CC0` License;
- [x] I've added the topic `rubyml` to the contributed repository if appropriate.

2023-06-09 15:22 UTC, arbox commented on readme.md
> +- 2020
I guess it should be 2022?

2023-06-12 18:53 UTC, thedayisntgray commented on readme.md
> +- 2020
Good catch!

2023-06-13 13:27 UTC, thedayisntgray commented
@arbox - Updated the year

2023-06-18 17:17 UTC, merged

2023-06-18 17:18 UTC, arbox commented
@thedayisntgray, thank you for your interest to contribute to this list!

2023-06-20 14:53 UTC, thedayisntgray commented
> @thedayisntgray, thank you for your interest to contribute to this list!

Thank You @arbox ,

This is such an incredible resource! I love it.

2024-02-16 21:14 UTC, myronyuktaras requested changes
**{{The evolution of the brain, the heart, the soul }}
,